CREATE DATABASE admin;
GRANT ALL PRIVILEGES ON DATABASE admin TO postgres;

CREATE DATABASE payment;
GRANT ALL PRIVILEGES ON DATABASE payment TO postgres;

CREATE DATABASE checkout;
GRANT ALL PRIVILEGES ON DATABASE checkout TO postgres;
