server:
  port: 8888

spring:
  application:
    name: config-server-mvc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erneani/reservago-config-repo.git
          search-paths: '{application}/{profile}'
          password: notusualpassword
          username: reservagochef
  security:
    user:
      name: root
      password: root
